### ISSUE TITLE
stuck at top of minimenu

### ISSUE THREAD

**Issue by monkeyd57** [donth77/loot-lookup-plugin#17]
can not seem to get the "lookup drops" option to not be at the top of the minimenu on any npc's even after uninstalling/reinstalling.
![minimenubug](https://user-images.githubusercontent.com/119544399/204927300-137d74a0-ef9d-4a98-9480-d6b0c8c1f9da.png)

**Comment by donth77** [comment]
This seems to have happened after the most recent game update on November 30th.

Fixed in this commit here:
[https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672](https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672)

plugin-hub PR:
[https://github.com/runelite/plugin-hub/pull/3623](https://github.com/runelite/plugin-hub/pull/3623)

**Comment by donth77** [comment]
@monkeyd57 
This seems to have happened after the most recent game update on November 30th.

Fixed in this commit here:
[https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672](https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672)

plugin-hub PR:
[https://github.com/runelite/plugin-hub/pull/3623](https://github.com/runelite/plugin-hub/pull/3623)
