### ISSUE TITLE
Lookup Drops is always the first option

### ISSUE THREAD

**Issue by timvdhoorn** [donth77/loot-lookup-plugin#18]
Suddenly the Loopup Drops option in de right-click menu is always on top, above Attack.

**Comment by donth77** [comment]
Looks like this happened after the most recent game update.

Fixed in this commit here:
https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672

plugin-hub PR:
https://github.com/runelite/plugin-hub/pull/3623

**Comment by donth77** [comment]
@timvdhoorn Looks like this happened after the most recent game update.

Fixed in this commit here:
https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672

plugin-hub PR:
https://github.com/runelite/plugin-hub/pull/3623

**Comment by donth77** [comment]
@timvdhoorn 
This seems to have happened after the most recent game update on November 30th.

Fixed in this commit here:
[https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672](https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672)

plugin-hub PR:
[https://github.com/runelite/plugin-hub/pull/3623](https://github.com/runelite/plugin-hub/pull/3623)

**Comment by donth77** [comment]
@timvdhoorn 
Looks like this happened after the most recent game update.

Fixed in this commit here:
[https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672](https://github.com/donth77/loot-lookup-plugin/commit/c2255394d09d81cdf0ece8a487afe635d3afe672)

plugin-hub PR:
[https://github.com/runelite/plugin-hub/pull/3623](https://github.com/runelite/plugin-hub/pull/3623)
